// Code generated by MockGen. DO NOT EDIT.
// Source: terminal_config_service.go
//
// Generated by this command:
//
//	mockgen -source=terminal_config_service.go -destination=mocks/mock_terminal_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "terminal_config/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockTerminalRepository is a mock of TerminalRepository interface.
type MockTerminalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTerminalRepositoryMockRecorder
	isgomock struct{}
}

// MockTerminalRepositoryMockRecorder is the mock recorder for MockTerminalRepository.
type MockTerminalRepositoryMockRecorder struct {
	mock *MockTerminalRepository
}

// NewMockTerminalRepository creates a new mock instance.
func NewMockTerminalRepository(ctrl *gomock.Controller) *MockTerminalRepository {
	mock := &MockTerminalRepository{ctrl: ctrl}
	mock.recorder = &MockTerminalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerminalRepository) EXPECT() *MockTerminalRepositoryMockRecorder {
	return m.recorder
}

// CreateTerminal mocks base method.
func (m *MockTerminalRepository) CreateTerminal(ctx context.Context, terminal *domain.Terminal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTerminal", ctx, terminal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTerminal indicates an expected call of CreateTerminal.
func (mr *MockTerminalRepositoryMockRecorder) CreateTerminal(ctx, terminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTerminal", reflect.TypeOf((*MockTerminalRepository)(nil).CreateTerminal), ctx, terminal)
}

// DeleteTerminal mocks base method.
func (m *MockTerminalRepository) DeleteTerminal(ctx context.Context, tid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTerminal", ctx, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTerminal indicates an expected call of DeleteTerminal.
func (mr *MockTerminalRepositoryMockRecorder) DeleteTerminal(ctx, tid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTerminal", reflect.TypeOf((*MockTerminalRepository)(nil).DeleteTerminal), ctx, tid)
}

// GetTerminalByTID mocks base method.
func (m *MockTerminalRepository) GetTerminalByTID(ctx context.Context, tid string) (*domain.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTerminalByTID", ctx, tid)
	ret0, _ := ret[0].(*domain.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTerminalByTID indicates an expected call of GetTerminalByTID.
func (mr *MockTerminalRepositoryMockRecorder) GetTerminalByTID(ctx, tid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTerminalByTID", reflect.TypeOf((*MockTerminalRepository)(nil).GetTerminalByTID), ctx, tid)
}

// ListTerminals mocks base method.
func (m *MockTerminalRepository) ListTerminals(ctx context.Context) ([]*domain.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTerminals", ctx)
	ret0, _ := ret[0].([]*domain.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTerminals indicates an expected call of ListTerminals.
func (mr *MockTerminalRepositoryMockRecorder) ListTerminals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTerminals", reflect.TypeOf((*MockTerminalRepository)(nil).ListTerminals), ctx)
}

// UpdateRefundAllowed mocks base method.
func (m *MockTerminalRepository) UpdateRefundAllowed(ctx context.Context, tid string, allowed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefundAllowed", ctx, tid, allowed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefundAllowed indicates an expected call of UpdateRefundAllowed.
func (mr *MockTerminalRepositoryMockRecorder) UpdateRefundAllowed(ctx, tid, allowed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefundAllowed", reflect.TypeOf((*MockTerminalRepository)(nil).UpdateRefundAllowed), ctx, tid, allowed)
}

// UpdateTerminal mocks base method.
func (m *MockTerminalRepository) UpdateTerminal(ctx context.Context, terminal *domain.Terminal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTerminal", ctx, terminal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTerminal indicates an expected call of UpdateTerminal.
func (mr *MockTerminalRepositoryMockRecorder) UpdateTerminal(ctx, terminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTerminal", reflect.TypeOf((*MockTerminalRepository)(nil).UpdateTerminal), ctx, terminal)
}

// MockTerminalConfigService is a mock of TerminalConfigService interface.
type MockTerminalConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockTerminalConfigServiceMockRecorder
	isgomock struct{}
}

// MockTerminalConfigServiceMockRecorder is the mock recorder for MockTerminalConfigService.
type MockTerminalConfigServiceMockRecorder struct {
	mock *MockTerminalConfigService
}

// NewMockTerminalConfigService creates a new mock instance.
func NewMockTerminalConfigService(ctrl *gomock.Controller) *MockTerminalConfigService {
	mock := &MockTerminalConfigService{ctrl: ctrl}
	mock.recorder = &MockTerminalConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerminalConfigService) EXPECT() *MockTerminalConfigServiceMockRecorder {
	return m.recorder
}

// CreateRandomTerminal mocks base method.
func (m *MockTerminalConfigService) CreateRandomTerminal(ctx context.Context) (*domain.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRandomTerminal", ctx)
	ret0, _ := ret[0].(*domain.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRandomTerminal indicates an expected call of CreateRandomTerminal.
func (mr *MockTerminalConfigServiceMockRecorder) CreateRandomTerminal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRandomTerminal", reflect.TypeOf((*MockTerminalConfigService)(nil).CreateRandomTerminal), ctx)
}

// CreateTerminal mocks base method.
func (m *MockTerminalConfigService) CreateTerminal(ctx context.Context, terminal *domain.Terminal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTerminal", ctx, terminal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTerminal indicates an expected call of CreateTerminal.
func (mr *MockTerminalConfigServiceMockRecorder) CreateTerminal(ctx, terminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTerminal", reflect.TypeOf((*MockTerminalConfigService)(nil).CreateTerminal), ctx, terminal)
}

// DeleteTerminal mocks base method.
func (m *MockTerminalConfigService) DeleteTerminal(ctx context.Context, tid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTerminal", ctx, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTerminal indicates an expected call of DeleteTerminal.
func (mr *MockTerminalConfigServiceMockRecorder) DeleteTerminal(ctx, tid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTerminal", reflect.TypeOf((*MockTerminalConfigService)(nil).DeleteTerminal), ctx, tid)
}

// GetTerminal mocks base method.
func (m *MockTerminalConfigService) GetTerminal(ctx context.Context, tid string) (*domain.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTerminal", ctx, tid)
	ret0, _ := ret[0].(*domain.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTerminal indicates an expected call of GetTerminal.
func (mr *MockTerminalConfigServiceMockRecorder) GetTerminal(ctx, tid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTerminal", reflect.TypeOf((*MockTerminalConfigService)(nil).GetTerminal), ctx, tid)
}

// ListTerminals mocks base method.
func (m *MockTerminalConfigService) ListTerminals(ctx context.Context) ([]*domain.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTerminals", ctx)
	ret0, _ := ret[0].([]*domain.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTerminals indicates an expected call of ListTerminals.
func (mr *MockTerminalConfigServiceMockRecorder) ListTerminals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTerminals", reflect.TypeOf((*MockTerminalConfigService)(nil).ListTerminals), ctx)
}

// UpdateRefundAllowed mocks base method.
func (m *MockTerminalConfigService) UpdateRefundAllowed(ctx context.Context, tid string, allowed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefundAllowed", ctx, tid, allowed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefundAllowed indicates an expected call of UpdateRefundAllowed.
func (mr *MockTerminalConfigServiceMockRecorder) UpdateRefundAllowed(ctx, tid, allowed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefundAllowed", reflect.TypeOf((*MockTerminalConfigService)(nil).UpdateRefundAllowed), ctx, tid, allowed)
}

// UpdateTerminal mocks base method.
func (m *MockTerminalConfigService) UpdateTerminal(ctx context.Context, terminal *domain.Terminal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTerminal", ctx, terminal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTerminal indicates an expected call of UpdateTerminal.
func (mr *MockTerminalConfigServiceMockRecorder) UpdateTerminal(ctx, terminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTerminal", reflect.TypeOf((*MockTerminalConfigService)(nil).UpdateTerminal), ctx, terminal)
}
