// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/http/handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/http/handlers.go -destination=internal/ports/http/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// SetupRoutes mocks base method.
func (m *MockHandlers) SetupRoutes() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupRoutes")
}

// SetupRoutes indicates an expected call of SetupRoutes.
func (mr *MockHandlersMockRecorder) SetupRoutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRoutes", reflect.TypeOf((*MockHandlers)(nil).SetupRoutes))
}
